
version: "3"

services:
  web:
    container_name: ui
    build:
      context: .
      dockerfile: ./apps/ui/Dockerfile
    restart: always
    ports:
      - 9001:80
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 9002:3000
    networks:
      - app_network

networks:
  app_network:
